ALTER TABLE employees ADD COLUMN IF NOT EXISTS annual_salary NUMERIC(15, 2) DEFAULT 0.00;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS branch_name VARCHAR(100);
ALTER TABLE employees ADD COLUMN IF NOT EXISTS job_location VARCHAR(100);
