
// Use window.location.hostname dynamically so it works on localhost and LAN IPs automatically
const dynamicHost = typeof window !== 'undefined' ? window.location.hostname : 'localhost';
export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || `http://${dynamicHost}:5000/api`;
export const BACKEND_URL = import.meta.env.DEV ? '' : import.meta.env.VITE_STATIC_BASE_URL;
export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  CHANGE_PASSWORD: '/change-password',
  DASHBOARD: '/dashboard',
  SUPER_ADMIN_DASHBOARD: '/dashboard/system',
  ADMIN_DASHBOARD: '/dashboard/organization',
  HR_DASHBOARD: '/dashboard/hr',
  MANAGER_DASHBOARD: '/dashboard/team',
  EMPLOYEE_DASHBOARD: '/dashboard/personal',
  DBA_DASHBOARD: '/dashboard/dba',
  SYSTEM_REPORTS: '/dashboard/system/reports',
  PRICING: '/pricing',
  FEATURES: '/features',
  BLOG: '/blog',
  CAREERS: '/careers',
  ABOUT: '/about',
  PAYMENT_SUCCESS: '/payment-success',
  PAYMENT_FAILURE: '/payment-failure',
  COMPLETE_PAYMENT: '/complete-payment',
  BILLING: '/billing',
  TENANTS: '/tenants',
  TENANTS_CREATE: '/tenants/create',
  SETTINGS_BILLING: '/settings/billing',
  PLANS: '/plans',
  COUPONS: '/coupons',
  SEARCH: '/search',
  NOTIFICATIONS: '/notifications',
  EMPLOYEES: '/dashboard/employees',
  EMPLOYEES_NEW: '/dashboard/employees/new',
  EMPLOYEES_ID: '/dashboard/employees/:id',
  EMPLOYEES_ID_EDIT: '/dashboard/employees/:id/edit',
  EMPLOYEES_ID_DOCUMENTS: '/dashboard/employees/:id/documents',
  ATTENDANCE: '/attendance',
  CALENDAR: '/calendar',
  INBOX: '/inbox',
  CHAT: '/chat',
  REPORTS: '/reports',
  ORGANISATION: '/organisation',
  SHIFTS: '/organization/shifts',
  SHIFT_ROSTER: '/organization/shift-roster',
  LEAVE: '/leave',
  LEAVE_SETTINGS: '/leave/settings',
  LEAVE_BALANCES: '/leave/balances',
  HOLIDAYS: '/holidays',
  DEPARTMENTS: '/departments',
  DESIGNATIONS: '/designations',
  ASSETS: '/assets',
  ASSETS_NEW: '/assets/new',
  ASSETS_REQUESTS: '/assets/requests',
  PROFILE: '/profile',
  SUBSCRIPTION: '/subscription',
  SETTINGS: '/settings',
  ACTIVITY: '/activity',
  ROLES_PERMISSIONS: '/roles-permissions',
  PERFORMANCE: '/performance',
  RECRUITMENT: '/recruitment',
  BONUS: '/bonus',
  ENGAGEMENT: '/engagement',
  COMPLIANCE: '/compliance',
  AI_INSIGHTS: '/ai-insights',
  PAYROLL: '/payroll',
  PAYROLL_DASHBOARD: '/payroll/dashboard',
  PAYROLL_FNF: '/payroll/fnf',
  PROJECTS: '/projects',
  PROJECTS_CLIENTS: '/projects/clients',
} as const;

export const ROLE_DASHBOARDS: Record<string, string> = {
  SUPER_ADMIN: ROUTES.SUPER_ADMIN_DASHBOARD,
  ADMIN: ROUTES.ADMIN_DASHBOARD,
  HR: ROUTES.HR_DASHBOARD,
  MANAGER: ROUTES.MANAGER_DASHBOARD,
  EMPLOYEE: ROUTES.EMPLOYEE_DASHBOARD,
};

